"""Updated

Revision ID: 0008f3357b07
Revises: 0f5516d23267
Create Date: 2023-05-12 14:15:50.331897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008f3357b07'
down_revision = '0f5516d23267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
