"""Структура БД

Revision ID: 14ee4c32e52b
Revises: 
Create Date: 2023-05-09 16:54:51.377911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ee4c32e52b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('Surname', sa.String(length=20), nullable=False),
    sa.Column('Patronymic', sa.String(length=20), nullable=False),
    sa.Column('Role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('news')
    op.drop_table('directing')
    # ### end Alembic commands ###
