"""Added table UserCourses

Revision ID: 1fb1bf857d4e
Revises: e72c20f69ebb
Create Date: 2023-05-14 22:17:35.767925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb1bf857d4e'
down_revision = 'e72c20f69ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
