"""Updated

Revision ID: 4e61e69b633c
Revises: 9f7e269abb0d
Create Date: 2023-05-12 14:12:18.112643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e61e69b633c'
down_revision = '9f7e269abb0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
