"""Updated

Revision ID: 50774321018b
Revises: 6838c715a0dc
Create Date: 2023-05-12 15:14:59.187983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50774321018b'
down_revision = '6838c715a0dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
