"""Added tablasasdasdsaASndereas

Revision ID: 541e794685b3
Revises: 8264c9d92700
Create Date: 2023-05-14 23:31:22.970523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541e794685b3'
down_revision = '8264c9d92700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserCourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.Text(), nullable=False),
    sa.Column('id_course', sa.Integer(), nullable=False),
    sa.Column('all_object', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserCourse')
    # ### end Alembic commands ###
