"""Added table UserCourses

Revision ID: 5b04e660dbc3
Revises: 1fb1bf857d4e
Create Date: 2023-05-14 22:46:50.021804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b04e660dbc3'
down_revision = '1fb1bf857d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
