"""Added table emialkd

Revision ID: 65dd90665da7
Revises: cbc3ee3e1d07
Create Date: 2023-05-14 23:09:13.596267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65dd90665da7'
down_revision = 'cbc3ee3e1d07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
