"""Updated

Revision ID: 660477513825
Revises: 4e61e69b633c
Create Date: 2023-05-12 14:14:34.114270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660477513825'
down_revision = '4e61e69b633c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('AdminCourses', sa.JSON(), nullable=True))
    op.drop_column('users', 'AdminCourse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('AdminCourse', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'AdminCourses')
    # ### end Alembic commands ###
