"""Updated

Revision ID: 6838c715a0dc
Revises: a3eb8ec13ad8
Create Date: 2023-05-12 15:11:43.918444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6838c715a0dc'
down_revision = 'a3eb8ec13ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
