"""Added table blabla

Revision ID: 74ac3515b24a
Revises: 5b04e660dbc3
Create Date: 2023-05-14 22:49:01.522428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ac3515b24a'
down_revision = '5b04e660dbc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
