"""Updated

Revision ID: 7f1f14058204
Revises: 86e5210bb8e1
Create Date: 2023-05-12 14:22:46.867104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1f14058204'
down_revision = '86e5210bb8e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
