"""Added table Rsdsda

Revision ID: 8264c9d92700
Revises: 65dd90665da7
Create Date: 2023-05-14 23:17:12.000406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8264c9d92700'
down_revision = '65dd90665da7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
