"""Updated

Revision ID: 9f7e269abb0d
Revises: be7ddba04743
Create Date: 2023-05-12 01:34:19.581896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7e269abb0d'
down_revision = 'be7ddba04743'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
