"""Updated

Revision ID: a3eb8ec13ad8
Revises: 7f1f14058204
Create Date: 2023-05-12 14:28:11.632721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3eb8ec13ad8'
down_revision = '7f1f14058204'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
