"""Updated

Revision ID: be7ddba04743
Revises: cfbb55717719
Create Date: 2023-05-12 00:22:38.072818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7ddba04743'
down_revision = 'cfbb55717719'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Courses', sa.Column('prevTitle', sa.Text(), nullable=False))
    op.add_column('Courses', sa.Column('prevImage', sa.Text(), nullable=False))
    op.add_column('Courses', sa.Column('prevAbout', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Courses', 'prevAbout')
    op.drop_column('Courses', 'prevImage')
    op.drop_column('Courses', 'prevTitle')
    # ### end Alembic commands ###
