"""Added table emialkd

Revision ID: cbc3ee3e1d07
Revises: 74ac3515b24a
Create Date: 2023-05-14 22:55:28.364276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc3ee3e1d07'
down_revision = '74ac3515b24a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
