"""Add new table Courses

Revision ID: cfbb55717719
Revises: df352e9b5396
Create Date: 2023-05-09 20:56:02.738724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbb55717719'
down_revision = 'df352e9b5396'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_direction', sa.String(length=40), nullable=False),
    sa.Column('all', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('Courses')
    # ### end Alembic commands ###
