"""Add a column to Users

Revision ID: df352e9b5396
Revises: 14ee4c32e52b
Create Date: 2023-05-09 20:26:08.226195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df352e9b5396'
down_revision = '14ee4c32e52b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('ActiveCourse', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('AdminCourse', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'AdminCourse')
    op.drop_column('users', 'ActiveCourse')
    op.drop_table('test')
    # ### end Alembic commands ###
