"""Updated

Revision ID: e72c20f69ebb
Revises: 6a706af883e9
Create Date: 2023-05-12 15:24:45.150059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72c20f69ebb'
down_revision = '6a706af883e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
